# Generated by Django 2.1.2 on 2018-10-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='urlmap',
            field=models.URLField(default=2, verbose_name='Карта'),
            preserve_default=False,
        ),
    ]
